// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestDal;

#nullable disable

namespace TestDal.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ManyTooMany2", b =>
                {
                    b.Property<int>("ManysId")
                        .HasColumnType("int");

                    b.Property<int>("TooMany2sId")
                        .HasColumnType("int");

                    b.HasKey("ManysId", "TooMany2sId");

                    b.HasIndex("TooMany2sId");

                    b.ToTable("ManyTooMany2");
                });

            modelBuilder.Entity("TestDal.Many", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Manys");
                });

            modelBuilder.Entity("TestDal.One", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("TooMany1Id")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TooMany1Id");

                    b.ToTable("Ones");
                });

            modelBuilder.Entity("TestDal.Parent", b =>
                {
                    b.Property<int>("ParentKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParentKey"), 1L, 1);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ParentKey");

                    b.ToTable("Parents");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Parent");
                });

            modelBuilder.Entity("TestDal.TooMany1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("TooMany1s");
                });

            modelBuilder.Entity("TestDal.TooMany2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("TooMany2s");
                });

            modelBuilder.Entity("TestDal.ToOne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RelatedToOneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedToOneId");

                    b.ToTable("ToOnes");
                });

            modelBuilder.Entity("TestDal.child", b =>
                {
                    b.HasBaseType("TestDal.Parent");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("child");
                });

            modelBuilder.Entity("TestDal.child2", b =>
                {
                    b.HasBaseType("TestDal.Parent");

                    b.Property<string>("hobbies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("child2");
                });

            modelBuilder.Entity("ManyTooMany2", b =>
                {
                    b.HasOne("TestDal.Many", null)
                        .WithMany()
                        .HasForeignKey("ManysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestDal.TooMany2", null)
                        .WithMany()
                        .HasForeignKey("TooMany2sId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestDal.One", b =>
                {
                    b.HasOne("TestDal.TooMany1", null)
                        .WithMany("TooManyOnes")
                        .HasForeignKey("TooMany1Id");
                });

            modelBuilder.Entity("TestDal.ToOne", b =>
                {
                    b.HasOne("TestDal.One", "RelatedToOne")
                        .WithMany()
                        .HasForeignKey("RelatedToOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedToOne");
                });

            modelBuilder.Entity("TestDal.TooMany1", b =>
                {
                    b.Navigation("TooManyOnes");
                });
#pragma warning restore 612, 618
        }
    }
}
